use qem::EditorTab;
use std::env;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = env::args_os().skip(1);
    let input = args
        .next()
        .map(PathBuf::from)
        .ok_or("usage: cargo run --example editor_session --features editor -- <input> <output>")?;
    let output = args
        .next()
        .map(PathBuf::from)
        .ok_or("usage: cargo run --example editor_session --features editor -- <input> <output>")?;

    let mut tab = EditorTab::new(1);
    tab.open_file(input.clone())?;
    let _ = tab
        .document_mut()
        .try_insert_text_at(0, 0, "// generated by qem example\n")?;
    tab.save_as(output.clone())?;

    println!("opened: {}", input.display());
    println!("saved copy: {}", output.display());
    println!(
        "cursor: line {}, column {}",
        tab.cursor().line(),
        tab.cursor().column()
    );

    Ok(())
}
