use qem::EditorTab;
use std::env;
use std::path::PathBuf;
use std::thread;
use std::time::{Duration, Instant};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = env::args_os().skip(1);
    let input = args
        .next()
        .map(PathBuf::from)
        .ok_or("usage: cargo run --example editor_session --features editor -- <input> <output>")?;
    let output = args
        .next()
        .map(PathBuf::from)
        .ok_or("usage: cargo run --example editor_session --features editor -- <input> <output>")?;

    let mut tab = EditorTab::new(1);
    tab.open_file_async(input.clone())?;
    wait_for_job(&mut tab, Duration::from_secs(5))?;
    let _ = tab
        .document_mut()
        .try_insert_text_at(0, 0, "// generated by qem example\n")?;
    tab.save_as_async(output.clone())?;
    wait_for_job(&mut tab, Duration::from_secs(5))?;

    println!("opened: {}", input.display());
    println!("saved copy: {}", output.display());
    println!(
        "cursor: line {}, column {}",
        tab.cursor().line(),
        tab.cursor().column()
    );

    Ok(())
}

fn wait_for_job(tab: &mut EditorTab, timeout: Duration) -> Result<(), Box<dyn std::error::Error>> {
    let deadline = Instant::now() + timeout;
    loop {
        if let Some(result) = tab.poll_background_job() {
            result?;
            return Ok(());
        }
        if !tab.is_busy() {
            return Ok(());
        }
        if Instant::now() >= deadline {
            return Err("background editor job timed out".into());
        }
        thread::sleep(Duration::from_millis(10));
    }
}
